dpc-sdp/tide_api

- composer.json
- src/Plugin/jsonapi/FieldEnhancer/EmbedVideoEnhancer.php
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-900
1. Removed protocol from generated YouTube/Vimeo embed uri.
Corresponding content-vic-gov-au PR: https://github.com/dpc-sdp/content-vic-gov-au/pull/236
> [SDPA-524][SDPA-900] Removed protocol from generated url.

- .circleci/config.yml
- Makefile
removed cli configuration from CI as it is not used anywhere
> removed cli configuration from CI

- composer.json
Story: https://digital-engagement.atlassian.net/browse/SDPA-958
CONTENT PR: https://github.com/dpc-sdp/content-vic-gov-au/pull/269
**Changed**
Apply a patch to fix an issue with json api enhancers and date range fields.
https://www.drupal.org/project/jsonapi_extras/issues/2953227
> [SDPA-958] Apply a patch to allow json api enhancers deal with date range

- src/Normalizer/OffsetPageNormalizer.php
- src/Query/OffsetPage.php
- src/Routing/TideApiParamEnhancer.php
- tide_api.services.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1110
1.  Replaced the JSONAPI ParamEnhancer and OffsetPage services with customised version to allow us to increase the limit on pagination.
> [SDPA-1110] Replaced JSONAPI Param Enhancer with customised version.

- src/Controller/TideApiController.php
Adding a fix for the cache issue on the home page route.
> Adding a fix for the cache issue on the home page route.

- .gitattributes
- tide_api.module
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1169
Content PR: https://github.com/dpc-sdp/content-vic-gov-au/pull/327
1.  Add randomizer parameters to avoid CDN cache
> [SDPA-1169] Add randomizer parameters to avoid CDN cache

- src/Plugin/jsonapi/FieldEnhancer/EmbedVideoEnhancer.php
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1743
1. Updated regex to correctly extract video IDs beginning with `-`.
> [SDPA-1743] Updated embed code regex.

- README.md
- src/Controller/TideApiController.php
- src/TideApiRedirectRepository.php
- tide_api.services.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-2031
1. Adding wildcard redirects to tide_api.
1. Wildcard redirects can be added using MySQL Like Syntax. The README has been updated to include instructions that the `%` can only be added to the end of a url to keep things simple.
> [SDPA-2031] : Adding wildcard redirects to tide_api.

- src/Controller/TideApiController.php
> [SDPA-2031] : Made a small change to ensure the default homepage route per site works.

- src/Controller/TideApiController.php
Extracting the query string from the incoming path in the getRoute function.
> Extracting the query string from the incoming path in the getRoute function.

- composer.json
- src/Controller/TideApiController.php
JIRA: 
* https://digital-engagement.atlassian.net/browse/SDPA-2286
* https://digital-engagement.atlassian.net/browse/SDPA-2287
> Fixed cached response after dispatching GET_ROUTE event.

- composer.json
- src/Controller/TideApiController.php
On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>
> Reverted JSON:API Extras to 3.4 and fixed typo in GET_ROUTE controller.

- config/optional/jsonapi_extras.jsonapi_resource_config.action--action.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.base_field_override--base_field_override.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.block--block.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.block_content_type--block_content_type.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.config_split--config_split.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.date_format--date_format.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.embed_button--embed_button.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.entity_form_display--entity_form_display.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.entity_form_mode--entity_form_mode.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.entity_view_display--entity_view_display.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.entity_view_mode--entity_view_mode.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.field_config--field_config.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.field_storage_config--field_storage_config.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.linkit_profile--linkit_profile.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.media_type--media_type.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.menu--menu.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.menu_link_content--menu_link_content.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--links.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--related_links.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.paragraphs_type--paragraphs_type.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.user_role--user_role.yml
- config/optional/jsonapi_extras.jsonapi_resource_config.view--view.yml
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-2192
> Reverted entity_id aliasing in favour of JSON:API 2.x.

- composer.json
> [SDPA-2523] Update Tide releases

- src/Controller/TideApiController.php
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-2271
On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>
> Fixed an issue in GET_ROUTE event logic.

- composer.json
- src/Controller/TideApiController.php
I've opened this PR to review why there's a diff in `composer.json` when the changes shown are already in the `develop` branch
> DO NOT MERGE

- composer.json
On-behalf-Of: @salsadigitalauorg <sonny@salsadigital.com.au>
> Release 1.2.5.

- config/optional/jsonapi.settings.yml
- tide_api.install
https://digital-engagement.atlassian.net/browse/SDPA-2966
> [SDPA-2966] add jsonapi configs

- src/Controller/TideApiController.php
JIRA: https://digital-engagement.atlassian.net/browse/SDPA-2972
On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>
> Added User cache context to GetRoute API.

- src/Controller/TideApiController.php
- src/Event/GetCacheIdEvent.php
- src/TideApiEvents.php
https://digital-engagement.atlassian.net/browse/SDPA-2992
> [SDPA-2992] fix cache issue

- src/Controller/TideApiController.php
https://digital-engagement.atlassian.net/browse/SDPA-2992
> [SDPA-2992] fixed api tests failing issue

- src/Plugin/jsonapi/FieldEnhancer/LinkEnhancer.php
- https://digital-engagement.atlassian.net/browse/SDPA-3158
- Updated LinkEnhancer to process internal link and internal link with an anchor tag.
- If alias or node is given it will create the url based on that.
- If anchor tag is added with the path, it will add the tag with the url.
> [SDPA-3158] Process internal link

- composer.json
- dev-tools.sh
- tide_api.info.yml
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3272
1.  Update Drupal to 8.7 and other updates as required.
> Remove drupal/jsonapi and update drupal 8.7.9

- dev-tools.sh
- tide_api.module
https://digital-engagement.atlassian.net/browse/DDIDO-93
> Used correct cache contexts for menu access check result.

- composer.json
- dev-tools.sh
https://digital-engagement.atlassian.net/browse/SDPA-4225
https://github.com/dpc-sdp/content-vic-gov-au/pull/867
> [SDPA-4225] updates tide_api to be compatible with Drupal 8.8.5

- modules/tide_share_link/tide_share_link.services.yml
https://digital-engagement.atlassian.net/browse/SDPSUP-2504
Increased the priority to 150 instead of the default 0 for share link.
> [SDPSUP-2504] Updated priority default value for share link.

- composer.json
JIRA ISSUE: https://digital-vic.atlassian.net/browse/SDPAP-6177
- Adds patch fix for page limit to be saved correctly.
> [SDPA-6177] Slow page render.

- modules/tide_content_collection/tide_content_collection.install
JIRA ISSUE: https://digital-vic.atlassian.net/browse/SDPAP-6177
Change:
Adds patch fix for page limit to be saved correctly.
> [SDPA-6177] Slow page render

- composer.json
- modules/tide_content_collection/config/install/core.entity_view_display.paragraph.content_collection.default.yml
- modules/tide_content_collection/tide_content_collection.install
**JIRA ISSUE:** https://digital-vic.atlassian.net/browse/SDPAP-6606
Hide content collection JSON raw data from content.
**Environment:** 
https://nginx-php.pr-133.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/
**Test results**: https://digital-vic.atlassian.net/browse/SDPAP-6606?focusedCommentId=135460
> [SDPAP-6606] Hide content collection JSON string from content.

- composer.json
**Jira** https://digital-vic.atlassian.net/browse/SRM-568
https://digital-vic.atlassian.net/browse/SRM-531
Changes:
1. Reroll patch for `jsonapi_extras`
> [SRM-531] Reroll `jsonapi_extras` patch

- modules/tide_content_collection/src/Plugin/Field/FieldWidget/ContentCollectionConfigurationWidget.php
**JIRA:** https://digital-vic.atlassian.net/browse/SDPAP-7028
**Change:**
- Remove mandatory checkbox and labels.
**Before:**
**After:**
> [SDPAP-7028] Content Collection remove mandatory checkbox.

- tests/behat/features/menu_items.feature
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-
1. Add behat testing to cover the existance of the endpoint added in R20-456 for Ripple 2
N/A
> [R20-456] Add test to cover the JSONAPI menu items endpoint added

- composer.json
- modules/tide_content_collection/config/install/core.entity_form_display.paragraph.content_collection_enhanced.default.yml
- modules/tide_content_collection/src/Plugin/Field/FieldWidget/ContentCollectionConfigurationWidget.php
- modules/tide_content_collection/tide_content_collection.install
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-7476
1. Enable CTA as new url field.
> [SDPAP-7476] CC New url field.

- modules/tide_content_collection/src/Plugin/Field/FieldWidget/ContentCollectionConfigurationWidget.php
https://digital-vic.atlassian.net/browse/SDPAP-7476
Remove the unneeded default value for `$element['callToAction']['text’]`
> [SDPAP-7476] Remove the unneeded default value

- modules/tide_content_collection/tide_content_collection.install
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-
1.
> Updated deprecated functions.

- composer.json
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-
https://www.drupal.org/project/drupal/issues/3088239
1. Updated patch for the issue Revisions on relations are not loaded correctly resulting in wrong data in includes as we are updating drupal core version.
> updated revision patch

- composer.json
**JIRA issue:** https://digital-vic.atlassian.net/browse/SDPAP-
1. Patch for jsonapi menu items has been updated for: 
"Allow filtering of response payload - https://www.drupal.org/project/jsonapi_menu_items/issues/3350524#comment-15577964": "https://www.drupal.org/files/issues/2024-05-02/3350524-filter_fields-6.patch"
> updated patch
